/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum17062025;

/**
 *
 * @author user
 */
public class menuminuman extends javax.swing.JFrame {

    private menuutama utama;
    
    public menuminuman() {
        initComponents();
    }
    
    public menuminuman(menuutama utama){
        this.utama = utama;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkesteh = new javax.swing.JCheckBox();
        chkkopsu = new javax.swing.JCheckBox();
        chkjus = new javax.swing.JCheckBox();
        chklemon = new javax.swing.JCheckBox();
        txtesteh = new javax.swing.JTextField();
        txtkopsu = new javax.swing.JTextField();
        txtjus = new javax.swing.JTextField();
        txtlemon = new javax.swing.JTextField();
        cbesteh = new javax.swing.JComboBox<>();
        cbkopsu = new javax.swing.JComboBox<>();
        cbjus = new javax.swing.JComboBox<>();
        cblemon = new javax.swing.JComboBox<>();
        txttotalesteh = new javax.swing.JTextField();
        txttotalkopsu = new javax.swing.JTextField();
        txttotaljus = new javax.swing.JTextField();
        txttotallemon = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU MINUMAN");

        chkesteh.setText("Es Teh Manis");
        chkesteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkestehActionPerformed(evt);
            }
        });

        chkkopsu.setText("Kopi Susu");
        chkkopsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkkopsuActionPerformed(evt);
            }
        });

        chkjus.setText("Jus Alpukat");
        chkjus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkjusActionPerformed(evt);
            }
        });

        chklemon.setText("Lemon The");
        chklemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklemonActionPerformed(evt);
            }
        });

        txtesteh.setText("0");

        txtkopsu.setText("0");

        txtjus.setText("0");

        txtlemon.setText("0");

        cbesteh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbesteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestehActionPerformed(evt);
            }
        });

        cbkopsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbkopsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkopsuActionPerformed(evt);
            }
        });

        cbjus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbjus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjusActionPerformed(evt);
            }
        });

        cblemon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cblemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblemonActionPerformed(evt);
            }
        });

        txttotalesteh.setText("0");

        txttotalkopsu.setText("0");

        txttotaljus.setText("0");

        txttotallemon.setText("0");

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        btnkembali.setText("Kembali ke Menu Utama");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        txttotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkesteh, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(chklemon)
                                .addComponent(chkkopsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkjus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtjus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(txtkopsu, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtesteh, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtlemon))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbesteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttotalesteh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbkopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttotalkopsu))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbjus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttotaljus))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cblemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttotallemon))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btntotal)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(135, 135, 135))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkesteh)
                    .addComponent(txtesteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbesteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalesteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkkopsu)
                        .addComponent(cbkopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttotalkopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkjus)
                    .addComponent(txtjus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotaljus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chklemon)
                    .addComponent(txtlemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cblemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotallemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnkembali)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkestehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkestehActionPerformed
        txtesteh.setText("5000");
    }//GEN-LAST:event_chkestehActionPerformed

    private void chkkopsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkkopsuActionPerformed
        txtkopsu.setText("15000");
    }//GEN-LAST:event_chkkopsuActionPerformed

    private void chkjusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkjusActionPerformed
        txtjus.setText("20000");
    }//GEN-LAST:event_chkjusActionPerformed

    private void chklemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklemonActionPerformed
        txtlemon.setText("15000");
    }//GEN-LAST:event_chklemonActionPerformed

    private void cbestehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestehActionPerformed
        int jml = (int)cbesteh.getSelectedIndex();
        int harga = Integer.parseInt(txtesteh.getText());
        double total = jml * harga;
        txttotalesteh.setText(Double.toString(total));
    }//GEN-LAST:event_cbestehActionPerformed

    private void cbkopsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkopsuActionPerformed
        int jml = (int)cbkopsu.getSelectedIndex();
        int harga = Integer.parseInt(txtkopsu.getText());
        double total = jml * harga;
        txttotalkopsu.setText(Double.toString(total));
    }//GEN-LAST:event_cbkopsuActionPerformed

    private void cbjusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjusActionPerformed
        int jml = (int)cbjus.getSelectedIndex();
        int harga = Integer.parseInt(txtjus.getText());
        double total = jml * harga;
        txttotaljus.setText(Double.toString(total));
    }//GEN-LAST:event_cbjusActionPerformed

    private void cblemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblemonActionPerformed
        int jml = (int)cblemon.getSelectedIndex();
        int harga = Integer.parseInt(txtlemon.getText());
        double total = jml * harga;
        txttotallemon.setText(Double.toString(total));
    }//GEN-LAST:event_cblemonActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        double esteh = Double.parseDouble(txttotalesteh.getText());
        double kopsu = Double.parseDouble(txttotalkopsu.getText());
        double jus = Double.parseDouble(txttotaljus.getText());
        double lemon = Double.parseDouble(txttotallemon.getText());
        
        double htotal = esteh + kopsu + jus + lemon;
        txttotal.setText(Double.toString(htotal));
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        String total = txttotal.getText();
        if(utama != null){
        utama.setTotalMinuman(total);
        }
        this.dispose(); //menutup jendela form menu makanan
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menuminuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cbesteh;
    private javax.swing.JComboBox<String> cbjus;
    private javax.swing.JComboBox<String> cbkopsu;
    private javax.swing.JComboBox<String> cblemon;
    private javax.swing.JCheckBox chkesteh;
    private javax.swing.JCheckBox chkjus;
    private javax.swing.JCheckBox chkkopsu;
    private javax.swing.JCheckBox chklemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtesteh;
    private javax.swing.JTextField txtjus;
    private javax.swing.JTextField txtkopsu;
    private javax.swing.JTextField txtlemon;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalesteh;
    private javax.swing.JTextField txttotaljus;
    private javax.swing.JTextField txttotalkopsu;
    private javax.swing.JTextField txttotallemon;
    // End of variables declaration//GEN-END:variables
}
