/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum17062025;

/**
 *
 * @author user
 */
public class menumakanan extends javax.swing.JFrame {

    
    private menuutama utama;
    
    public menumakanan() {
        initComponents();
    }
    
    public menumakanan(menuutama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chknasgor = new javax.swing.JCheckBox();
        chkmigor = new javax.swing.JCheckBox();
        chksate = new javax.swing.JCheckBox();
        chksoto = new javax.swing.JCheckBox();
        txtnasgor = new javax.swing.JTextField();
        txtmigor = new javax.swing.JTextField();
        txtsate = new javax.swing.JTextField();
        txtsoto = new javax.swing.JTextField();
        cbnasgor = new javax.swing.JComboBox<>();
        cbmigor = new javax.swing.JComboBox<>();
        cbsate = new javax.swing.JComboBox<>();
        cbsoto = new javax.swing.JComboBox<>();
        txttotalnasgor = new javax.swing.JTextField();
        txttotalmigor = new javax.swing.JTextField();
        txttotalsate = new javax.swing.JTextField();
        txttotalsoto = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU MAKANAN");

        chknasgor.setText("Nasi Goreng");
        chknasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chknasgorActionPerformed(evt);
            }
        });

        chkmigor.setText("Mie Goreng");
        chkmigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmigorActionPerformed(evt);
            }
        });

        chksate.setText("Sate");
        chksate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksateActionPerformed(evt);
            }
        });

        chksoto.setText("Soto");
        chksoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksotoActionPerformed(evt);
            }
        });

        cbnasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnasgorActionPerformed(evt);
            }
        });

        cbmigor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbmigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmigorActionPerformed(evt);
            }
        });

        cbsate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbsate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsateActionPerformed(evt);
            }
        });

        cbsoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsotoActionPerformed(evt);
            }
        });

        txttotalnasgor.setText("0");
        txttotalnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalnasgorActionPerformed(evt);
            }
        });

        txttotalmigor.setText("0");

        txttotalsate.setText("0");
        txttotalsate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalsateActionPerformed(evt);
            }
        });

        txttotalsoto.setText("0");

        txttotal.setText("0");

        btnkembali.setText("Kembali ke Menu Utama");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chknasgor)
                                        .addComponent(chkmigor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chksate, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chksoto)
                                        .addGap(43, 43, 43)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnasgor, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtmigor)
                                    .addComponent(txtsate)
                                    .addComponent(txtsoto))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btntotal))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttotalmigor)
                            .addComponent(txttotalnasgor)
                            .addComponent(txttotalsate)
                            .addComponent(txttotalsoto, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txttotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chknasgor)
                    .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkmigor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttotalmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotalsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chksate))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chksoto)
                    .addComponent(txtsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntotal))
                .addGap(18, 18, 18)
                .addComponent(btnkembali)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chksotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksotoActionPerformed
        txtsoto.setText("15000");
    }//GEN-LAST:event_chksotoActionPerformed

    private void txttotalsateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalsateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalsateActionPerformed

    private void txttotalnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalnasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalnasgorActionPerformed

    private void chknasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chknasgorActionPerformed
       txtnasgor.setText("15000");
    }//GEN-LAST:event_chknasgorActionPerformed

    private void chkmigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmigorActionPerformed
        txtmigor.setText("12500");
    }//GEN-LAST:event_chkmigorActionPerformed

    private void chksateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksateActionPerformed
        txtsate.setText("10000");
    }//GEN-LAST:event_chksateActionPerformed

    private void cbnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnasgorActionPerformed
        int jml = (int)cbnasgor.getSelectedIndex();
        int harga = Integer.parseInt(txtnasgor.getText());
        double total = jml * harga;
        txttotalnasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbnasgorActionPerformed

    private void cbmigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmigorActionPerformed
        int jml = (int)cbmigor.getSelectedIndex();
        int harga = Integer.parseInt(txtmigor.getText());
        double total = jml * harga;
        txttotalmigor.setText(Double.toString(total));
    }//GEN-LAST:event_cbmigorActionPerformed

    private void cbsateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsateActionPerformed
        int jml = (int)cbsate.getSelectedIndex();
        int harga = Integer.parseInt(txtsate.getText());
        double total = jml * harga;
        txttotalsate.setText(Double.toString(total));
    }//GEN-LAST:event_cbsateActionPerformed

    private void cbsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsotoActionPerformed
        int jml = (int)cbsoto.getSelectedIndex();
        int harga = Integer.parseInt(txtsoto.getText());
        double total = jml * harga;
        txttotalsoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbsotoActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        double nasgor = Double.parseDouble(txttotalnasgor.getText());
        double migor = Double.parseDouble(txttotalmigor.getText());
        double sate = Double.parseDouble(txttotalsate.getText());
        double soto = Double.parseDouble(txttotalsoto.getText());
        double htotal = nasgor + migor + sate + soto;
        txttotal.setText(String.valueOf(htotal));
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        String total = txttotal.getText();
        utama.setTotalMakanan(total);
        this.dispose(); //menutup jendela form menu makanan
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menumakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cbmigor;
    private javax.swing.JComboBox<String> cbnasgor;
    private javax.swing.JComboBox<String> cbsate;
    private javax.swing.JComboBox<String> cbsoto;
    private javax.swing.JCheckBox chkmigor;
    private javax.swing.JCheckBox chknasgor;
    private javax.swing.JCheckBox chksate;
    private javax.swing.JCheckBox chksoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtmigor;
    private javax.swing.JTextField txtnasgor;
    private javax.swing.JTextField txtsate;
    private javax.swing.JTextField txtsoto;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalmigor;
    private javax.swing.JTextField txttotalnasgor;
    private javax.swing.JTextField txttotalsate;
    private javax.swing.JTextField txttotalsoto;
    // End of variables declaration//GEN-END:variables
}
