/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasPenggantiLibur;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class pola extends javax.swing.JFrame {

    /**
     * Creates new form pola
     */
    public pola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baris = new javax.swing.JLabel();
        txtbaris = new javax.swing.JTextField();
        kolom = new javax.swing.JLabel();
        cbopsi = new javax.swing.JComboBox<>();
        pilihanpola = new javax.swing.JLabel();
        cbpola = new javax.swing.JLabel();
        txtkolom = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        baris.setText("Masukkan Baris");

        txtbaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarisActionPerformed(evt);
            }
        });

        kolom.setText("Masukkan Kolom");

        cbopsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pola", "Tambah ", "Kurang", "Kali", "Bagi" }));
        cbopsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopsiActionPerformed(evt);
            }
        });

        pilihanpola.setText("Masukkan Pilihan Pola");

        cbpola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbpola.setText("POLA PERULANGAN BERSARANG");

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(cbpola)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pilihanpola, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kolom, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(baris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbaris)
                            .addComponent(txtkolom, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnproses)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbpola)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baris)
                    .addComponent(txtbaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolom)
                    .addComponent(txtkolom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihanpola)
                    .addComponent(cbopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnproses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarisActionPerformed

    }//GEN-LAST:event_txtbarisActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
       try{
            int a = Integer.parseInt(txtbaris.getText());
            int b = Integer.parseInt(txtkolom.getText());
            int pola = (int)cbopsi.getSelectedIndex();
            StringBuilder output = new StringBuilder();
            int i, j;

            switch(pola) {
                case 1: {
                    for(i = 0; i < a; i++) {
                        for(j = 0; j < b; j++) {
                            if(i == 0 || i == a - 1 || j == 0 || j == a - 1) {
                                output.append(" * ");
                            }else {
                                output.append("   ");
                            }
                        }
                        output.append("\n");
                    }
                }break;
                case 2: {
                    for(i = 0; i < a; i++) {
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        output.append("\n\n");
                    }
                }break;
                case 3: {
                    for(i = 0; i < a; i++) {
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        for(j = 1; j <= i; j++) {
                            output.append(" * ");
                        }
                        output.append("\n\n");
                    }
                }break;
                case 4: {
                    for(i = 0; i < a; i++) {
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        output.append("\n\n");
                    }
                }break;
                case 5: {
                    for(i = 0; i < a; i++) {
                        for(j = 0; j <= i; j++) {
                            output.append("  ");
                        }
                        for(j = 0; j < b; j++) {
                            output.append("  *  ");
                        }
                        output.append("\n\n");
                    }
                }break;
            }
            areaHasil.setText(output.toString());
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input berupa angka", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtbaris.setText("");
            txtkolom.setText("");
            txtbaris.requestFocus();
        }catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
       
    }//GEN-LAST:event_btnprosesActionPerformed

    private void cbopsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbopsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JLabel baris;
    private javax.swing.JButton btnproses;
    private javax.swing.JComboBox<String> cbopsi;
    private javax.swing.JLabel cbpola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kolom;
    private javax.swing.JLabel pilihanpola;
    private javax.swing.JTextField txtbaris;
    private javax.swing.JTextField txtkolom;
    // End of variables declaration//GEN-END:variables
}
